import { Handle, Position } from 'reactflow';
import { Badge } from '@/components/ui/badge';
import { Users, TrendingUp, MapPin, Building2 } from 'lucide-react';
import type { Microsegment } from '@/types';

interface MicrosegmentNodeData {
  label: string;
  microsegment: Microsegment;
  viewMode?: 'design' | 'analytics';
  metrics?: {
    entered: number;
    converted: number;
    conversionRate: number;
  };
}

interface MicrosegmentNodeProps {
  data: MicrosegmentNodeData;
  isConnectable: boolean;
}

export function MicrosegmentNode({ data, isConnectable }: MicrosegmentNodeProps) {
  const { microsegment } = data;
  const isAnalyticsMode = data.viewMode === 'analytics';
  const metrics = data.metrics;

  // Determine color based on engagement or criteria
  const getColorClass = () => {
    if (microsegment.criteria.behavioral?.previousCampaignResponse === 'HIGH') {
      return 'bg-emerald-100 border-emerald-300 text-emerald-800';
    } else if (microsegment.criteria.behavioral?.previousCampaignResponse === 'MEDIUM') {
      return 'bg-amber-100 border-amber-300 text-amber-800';
    } else if (microsegment.criteria.behavioral?.previousCampaignResponse === 'LOW') {
      return 'bg-slate-100 border-slate-300 text-slate-800';
    }
    return 'bg-blue-100 border-blue-300 text-blue-800'; // New to brand
  };

  const conversionRate = metrics
    ? ((metrics.converted / metrics.entered) * 100).toFixed(1)
    : null;

  return (
    <div
      className={`relative px-4 py-3 rounded-lg border-2 min-w-[220px] group ${getColorClass()} transition-all hover:shadow-md`}
    >
      {/* Left Handle (Primary Input for left-to-right flow) */}
      <Handle
        type="target"
        position={Position.Left}
        id="left"
        isConnectable={isConnectable}
        className="!w-3 !h-3 !bg-gray-400 !border-2 !border-white"
      />

      {/* Top Handle (Secondary Input) */}
      <Handle
        type="target"
        position={Position.Top}
        id="top"
        isConnectable={isConnectable}
        className="!w-3 !h-3 !bg-gray-400 !border-2 !border-white opacity-0 group-hover:opacity-100 transition-opacity"
      />

      {/* Header */}
      <div className="flex items-center gap-2 mb-2">
        <Users className="h-4 w-4 flex-shrink-0" />
        <span className="font-semibold text-sm">{microsegment.name}</span>
      </div>

      {/* Design Mode Content */}
      {!isAnalyticsMode && (
        <div className="space-y-2">
          <p className="text-xs text-muted-foreground line-clamp-2">{microsegment.description}</p>

          <div className="flex items-center gap-2">
            <Badge variant="secondary" className="text-xs font-mono">
              {microsegment.estimatedCount.toLocaleString()} HCPs
            </Badge>
            {microsegment.autoGenerated && (
              <Badge variant="outline" className="text-xs">
                Auto
              </Badge>
            )}
          </div>

          {/* Criteria Highlights */}
          <div className="space-y-1">
            {microsegment.criteria.behavioral?.engagementScore && (
              <div className="flex items-center gap-1 text-xs">
                <TrendingUp className="h-3 w-3" />
                <span>
                  Engagement: {microsegment.criteria.behavioral.engagementScore.min}-
                  {microsegment.criteria.behavioral.engagementScore.max}
                </span>
              </div>
            )}

            {microsegment.criteria.demographics?.region && (
              <div className="flex items-center gap-1 text-xs">
                <MapPin className="h-3 w-3" />
                <span className="truncate">
                  {microsegment.criteria.demographics.region.slice(0, 2).join(', ')}
                  {microsegment.criteria.demographics.region.length > 2 &&
                    ` +${microsegment.criteria.demographics.region.length - 2}`}
                </span>
              </div>
            )}

            {microsegment.criteria.institutional?.practiceSetting && (
              <div className="flex items-center gap-1 text-xs">
                <Building2 className="h-3 w-3" />
                <span className="truncate">
                  {microsegment.criteria.institutional.practiceSetting[0]}
                </span>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Analytics Mode Content */}
      {isAnalyticsMode && metrics && (
        <div className="space-y-2">
          <div className="flex justify-between text-xs">
            <span className="text-muted-foreground">Entered</span>
            <span className="font-semibold">{metrics.entered.toLocaleString()}</span>
          </div>
          <div className="flex justify-between text-xs">
            <span className="text-muted-foreground">Converted</span>
            <span className="font-semibold text-green-600">
              {metrics.converted.toLocaleString()} ({conversionRate}%)
            </span>
          </div>

          <div className="pt-2 mt-2 border-t">
            <Badge variant="secondary" className="text-xs font-mono">
              {microsegment.estimatedCount.toLocaleString()} total
            </Badge>
          </div>
        </div>
      )}

      {/* Right Handle */}
      <Handle
        type="source"
        position={Position.Right}
        id="right"
        isConnectable={isConnectable}
        className="!w-3 !h-3 !bg-gray-400 !border-2 !border-white opacity-0 group-hover:opacity-100 transition-opacity"
      />

      {/* Bottom Handle */}
      <Handle
        type="source"
        position={Position.Bottom}
        id="bottom"
        isConnectable={isConnectable}
        className="!w-3 !h-3 !bg-gray-400 !border-2 !border-white opacity-0 group-hover:opacity-100 transition-opacity"
      />
    </div>
  );
}
