import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Microsegment, MicrosegmentCriteria, Segment, ContentChannel } from '@/types';
import { Users, Trash2, Plus, Sparkles } from 'lucide-react';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';

interface MicrosegmentGeneratorProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  segment: Segment;
  onConfirm: (microsegments: Microsegment[]) => void;
}

// Auto-generation algorithm
function generateMicrosegments(segment: Segment): Microsegment[] {
  const microsegments: Microsegment[] = [];
  const baseDate = new Date();

  // Calculate distribution based on segment size
  const totalCount = segment.estimatedCount;

  // Generate 4 microsegments based on engagement patterns
  const segmentConfigs = [
    {
      name: 'High Engagers - Urban Academic Centers',
      description: 'Top 25% engagement, urban academic medical centers, high prescription volume',
      percentage: 0.25,
      criteria: {
        demographics: {
          region: ['Northeast', 'West Coast', 'Mid-Atlantic'],
        },
        behavioral: {
          engagementScore: { min: 75, max: 100 },
          previousCampaignResponse: 'HIGH' as const,
          channelPreference: ['EMAIL', 'WEB'] as ContentChannel[],
        },
        institutional: {
          practiceSetting: ['Academic Medical Center'],
          volumeCategory: 'HIGH' as const,
          tier: 1,
        },
      },
    },
    {
      name: 'Medium Engagers - Private Practice',
      description: 'Mid-tier engagement, private practice settings, moderate volume',
      percentage: 0.35,
      criteria: {
        demographics: {
          region: ['Southeast', 'Midwest', 'Southwest'],
        },
        behavioral: {
          engagementScore: { min: 50, max: 74 },
          previousCampaignResponse: 'MEDIUM' as const,
          channelPreference: ['EMAIL', 'PAID_MEDIA'] as ContentChannel[],
        },
        institutional: {
          practiceSetting: ['Private Practice', 'Group Practice'],
          volumeCategory: 'MEDIUM' as const,
          tier: 2,
        },
      },
    },
    {
      name: 'Low Engagers - Rural Community',
      description: 'Lower engagement, rural/community settings, lower prescription volume',
      percentage: 0.25,
      criteria: {
        demographics: {
          region: ['Mountain', 'Plains', 'Rural'],
        },
        behavioral: {
          engagementScore: { min: 0, max: 49 },
          previousCampaignResponse: 'LOW' as const,
          channelPreference: ['PAID_MEDIA'] as ContentChannel[],
        },
        institutional: {
          practiceSetting: ['Community Hospital', 'Rural Clinic'],
          volumeCategory: 'LOW' as const,
          tier: 3,
        },
      },
    },
    {
      name: 'New to Brand - High Volume',
      description: 'Never interacted with brand, but high prescription volume potential',
      percentage: 0.15,
      criteria: {
        behavioral: {
          lastInteractionDays: 999, // Never interacted
          channelPreference: ['EMAIL', 'PAID_MEDIA', 'WEB'] as ContentChannel[],
        },
        institutional: {
          volumeCategory: 'HIGH' as const,
          tier: 1,
        },
      },
    },
  ];

  segmentConfigs.forEach((config, idx) => {
    microsegments.push({
      id: `MSEG-${Date.now()}-${idx}`,
      parentSegmentId: segment.id,
      name: config.name,
      description: config.description,
      criteria: config.criteria,
      estimatedCount: Math.floor(totalCount * config.percentage),
      autoGenerated: true,
      isActive: true,
      createdAt: baseDate,
    });
  });

  return microsegments;
}

export function MicrosegmentGenerator({
  open,
  onOpenChange,
  segment,
  onConfirm,
}: MicrosegmentGeneratorProps) {
  const [microsegments, setMicrosegments] = useState<Microsegment[]>(() =>
    generateMicrosegments(segment)
  );

  const handleUpdateMicrosegment = (id: string, field: keyof Microsegment, value: any) => {
    setMicrosegments((prev) =>
      prev.map((ms) => (ms.id === id ? { ...ms, [field]: value } : ms))
    );
  };

  const handleUpdateCriteria = (
    id: string,
    section: keyof MicrosegmentCriteria,
    field: string,
    value: any
  ) => {
    setMicrosegments((prev) =>
      prev.map((ms) => {
        if (ms.id === id) {
          return {
            ...ms,
            criteria: {
              ...ms.criteria,
              [section]: {
                ...ms.criteria[section],
                [field]: value,
              },
            },
          };
        }
        return ms;
      })
    );
  };

  const handleRemoveMicrosegment = (id: string) => {
    setMicrosegments((prev) => prev.filter((ms) => ms.id !== id));
  };

  const handleAddMicrosegment = () => {
    const newMicrosegment: Microsegment = {
      id: `MSEG-${Date.now()}-custom`,
      parentSegmentId: segment.id,
      name: 'Custom Microsegment',
      description: 'Manually defined microsegment',
      criteria: {},
      estimatedCount: 0,
      autoGenerated: false,
      isActive: true,
      createdAt: new Date(),
    };
    setMicrosegments((prev) => [...prev, newMicrosegment]);
  };

  const handleConfirm = () => {
    onConfirm(microsegments);
    onOpenChange(false);
  };

  const totalEstimated = microsegments.reduce((sum, ms) => sum + ms.estimatedCount, 0);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-6xl max-h-[90vh] overflow-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary" />
            Auto-Generated Microsegments
          </DialogTitle>
          <DialogDescription>
            Based on <strong>{segment.name}</strong> ({segment.estimatedCount.toLocaleString()}{' '}
            HCPs), we've generated {microsegments.length} microsegments. You can edit names,
            descriptions, criteria, or add/remove microsegments.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 mt-4">
          {/* Summary Card */}
          <Card>
            <CardHeader>
              <CardTitle className="text-sm flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <Users className="h-4 w-4" />
                  Summary
                </span>
                <Badge variant="secondary">
                  {totalEstimated.toLocaleString()} / {segment.estimatedCount.toLocaleString()} HCPs
                </Badge>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex gap-2 flex-wrap">
                {microsegments.map((ms) => (
                  <Badge key={ms.id} variant="outline">
                    {ms.name}: {ms.estimatedCount.toLocaleString()}
                  </Badge>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Microsegment Cards */}
          {microsegments.map((ms, idx) => (
            <Card key={ms.id} className="relative">
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <CardTitle className="text-sm flex items-center gap-2">
                      {ms.autoGenerated && (
                        <Badge variant="secondary" className="text-xs">
                          Auto-generated
                        </Badge>
                      )}
                      Microsegment {idx + 1}
                    </CardTitle>
                    <CardDescription className="mt-1">
                      {ms.estimatedCount.toLocaleString()} HCPs (
                      {((ms.estimatedCount / segment.estimatedCount) * 100).toFixed(1)}%)
                    </CardDescription>
                  </div>
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => handleRemoveMicrosegment(ms.id)}
                    disabled={microsegments.length === 1}
                  >
                    <Trash2 className="h-4 w-4 text-destructive" />
                  </Button>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                {/* Name */}
                <div className="space-y-2">
                  <Label htmlFor={`name-${ms.id}`}>Name</Label>
                  <Input
                    id={`name-${ms.id}`}
                    value={ms.name}
                    onChange={(e) => handleUpdateMicrosegment(ms.id, 'name', e.target.value)}
                    placeholder="Microsegment name"
                  />
                </div>

                {/* Description */}
                <div className="space-y-2">
                  <Label htmlFor={`description-${ms.id}`}>Description</Label>
                  <Textarea
                    id={`description-${ms.id}`}
                    value={ms.description}
                    onChange={(e) => handleUpdateMicrosegment(ms.id, 'description', e.target.value)}
                    placeholder="Brief description of this microsegment"
                    rows={2}
                  />
                </div>

                {/* Estimated Count */}
                <div className="space-y-2">
                  <Label htmlFor={`count-${ms.id}`}>Estimated Count</Label>
                  <Input
                    id={`count-${ms.id}`}
                    type="number"
                    value={ms.estimatedCount}
                    onChange={(e) =>
                      handleUpdateMicrosegment(ms.id, 'estimatedCount', parseInt(e.target.value) || 0)
                    }
                    placeholder="Number of HCPs"
                  />
                </div>

                {/* Criteria Summary */}
                <div className="space-y-2">
                  <Label>Targeting Criteria</Label>
                  <div className="grid grid-cols-2 gap-4">
                    {/* Behavioral Criteria */}
                    {ms.criteria.behavioral && (
                      <div className="space-y-2">
                        <p className="text-xs font-medium text-muted-foreground">Behavioral</p>
                        {ms.criteria.behavioral.engagementScore && (
                          <div className="space-y-1">
                            <Label className="text-xs">Engagement Score</Label>
                            <div className="flex gap-2 items-center">
                              <Input
                                type="number"
                                value={ms.criteria.behavioral.engagementScore.min}
                                onChange={(e) =>
                                  handleUpdateCriteria(
                                    ms.id,
                                    'behavioral',
                                    'engagementScore',
                                    {
                                      ...ms.criteria.behavioral!.engagementScore,
                                      min: parseInt(e.target.value) || 0,
                                    }
                                  )
                                }
                                className="h-8 text-xs"
                                placeholder="Min"
                              />
                              <span className="text-xs text-muted-foreground">to</span>
                              <Input
                                type="number"
                                value={ms.criteria.behavioral.engagementScore.max}
                                onChange={(e) =>
                                  handleUpdateCriteria(
                                    ms.id,
                                    'behavioral',
                                    'engagementScore',
                                    {
                                      ...ms.criteria.behavioral!.engagementScore,
                                      max: parseInt(e.target.value) || 100,
                                    }
                                  )
                                }
                                className="h-8 text-xs"
                                placeholder="Max"
                              />
                            </div>
                          </div>
                        )}
                        {ms.criteria.behavioral.previousCampaignResponse && (
                          <div className="space-y-1">
                            <Label className="text-xs">Previous Response</Label>
                            <Select
                              value={ms.criteria.behavioral.previousCampaignResponse}
                              onValueChange={(value: 'HIGH' | 'MEDIUM' | 'LOW') =>
                                handleUpdateCriteria(
                                  ms.id,
                                  'behavioral',
                                  'previousCampaignResponse',
                                  value
                                )
                              }
                            >
                              <SelectTrigger className="h-8 text-xs">
                                <SelectValue />
                              </SelectTrigger>
                              <SelectContent>
                                <SelectItem value="HIGH">High</SelectItem>
                                <SelectItem value="MEDIUM">Medium</SelectItem>
                                <SelectItem value="LOW">Low</SelectItem>
                              </SelectContent>
                            </Select>
                          </div>
                        )}
                      </div>
                    )}

                    {/* Institutional Criteria */}
                    {ms.criteria.institutional && (
                      <div className="space-y-2">
                        <p className="text-xs font-medium text-muted-foreground">Institutional</p>
                        {ms.criteria.institutional.volumeCategory && (
                          <div className="space-y-1">
                            <Label className="text-xs">Volume Category</Label>
                            <Select
                              value={ms.criteria.institutional.volumeCategory}
                              onValueChange={(value: 'HIGH' | 'MEDIUM' | 'LOW') =>
                                handleUpdateCriteria(ms.id, 'institutional', 'volumeCategory', value)
                              }
                            >
                              <SelectTrigger className="h-8 text-xs">
                                <SelectValue />
                              </SelectTrigger>
                              <SelectContent>
                                <SelectItem value="HIGH">High</SelectItem>
                                <SelectItem value="MEDIUM">Medium</SelectItem>
                                <SelectItem value="LOW">Low</SelectItem>
                              </SelectContent>
                            </Select>
                          </div>
                        )}
                        {ms.criteria.institutional.tier && (
                          <div className="space-y-1">
                            <Label className="text-xs">Tier</Label>
                            <Input
                              type="number"
                              value={ms.criteria.institutional.tier}
                              onChange={(e) =>
                                handleUpdateCriteria(
                                  ms.id,
                                  'institutional',
                                  'tier',
                                  parseInt(e.target.value) || 1
                                )
                              }
                              className="h-8 text-xs"
                              min="1"
                              max="3"
                            />
                          </div>
                        )}
                      </div>
                    )}

                    {/* Demographics */}
                    {ms.criteria.demographics && ms.criteria.demographics.region && (
                      <div className="col-span-2 space-y-1">
                        <Label className="text-xs">Regions</Label>
                        <div className="flex flex-wrap gap-1">
                          {ms.criteria.demographics.region.map((region) => (
                            <Badge key={region} variant="secondary" className="text-xs">
                              {region}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}

          {/* Add Microsegment Button */}
          <Button
            variant="outline"
            className="w-full"
            onClick={handleAddMicrosegment}
            disabled={microsegments.length >= 6}
          >
            <Plus className="h-4 w-4 mr-2" />
            Add Custom Microsegment
          </Button>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button onClick={handleConfirm} disabled={microsegments.length === 0}>
            <Users className="h-4 w-4 mr-2" />
            Create {microsegments.length} Microsegment{microsegments.length !== 1 ? 's' : ''}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
