import { Brand, Product, Campaign, Claim, MLRCase, Segment, User, Dashboard, Microsegment, ContentResonancePrediction, IDRegistryEntry } from '@/types';

export const mockUser: User = {
  id: '1',
  name: 'Dr Sarah Johnson',
  email: 'sarah.johnson@pharma.com',
  role: 'ADMIN',
  status: 'active',
  createdAt: new Date('2024-01-01'),
};

export const mockBrands: Brand[] = [
  { id: '1', name: 'CardioLife', therapeuticArea: 'Cardiovascular' },
  { id: '2', name: 'NeuroCare', therapeuticArea: 'Neurology' },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    brandId: '1',
    name: 'CardioLife 10mg',
    indications: ['Hypertension', 'Heart Failure'],
    markets: ['UK', 'EU', 'US'],
  },
  {
    id: '2',
    brandId: '1',
    name: 'CardioLife 20mg',
    indications: ['Hypertension'],
    markets: ['UK', 'EU'],
  },
  {
    id: '3',
    brandId: '2',
    name: 'NeuroCare XR',
    indications: ['Multiple Sclerosis'],
    markets: ['UK', 'EU', 'US', 'CA'],
  },
];

export const mockClaims: Claim[] = [
  {
    id: '1',
    productId: '1',
    claimText: 'Reduces systolic blood pressure by 20mmHg on average',
    claimCategory: 'Efficacy',
    version: 1,
    status: 'APPROVED',
    effectiveFrom: new Date('2024-01-01'),
    createdBy: '1',
    evidenceDocuments: [
      {
        id: '1',
        claimId: '1',
        title: 'PROGRESS Trial Results',
        sourceType: 'Clinical Trial',
        url: '/evidence/progress-trial.pdf',
        uploadedBy: '1',
        uploadedAt: new Date('2024-01-01'),
        checksum: 'abc123',
      },
    ],
  },
  {
    id: '2',
    productId: '1',
    claimText: 'Well tolerated in elderly populations',
    claimCategory: 'Safety',
    version: 1,
    status: 'APPROVED',
    effectiveFrom: new Date('2024-02-01'),
    createdBy: '1',
    evidenceDocuments: [
      {
        id: '2',
        claimId: '2',
        title: 'Elderly Safety Study',
        sourceType: 'Post-Marketing Study',
        url: '/evidence/elderly-safety.pdf',
        uploadedBy: '1',
        uploadedAt: new Date('2024-02-01'),
        checksum: 'def456',
      },
    ],
  },
  {
    id: '3',
    productId: '3',
    claimText: 'Reduces relapse rate by 45%',
    claimCategory: 'Efficacy',
    version: 1,
    status: 'UNDER_REVIEW',
    effectiveFrom: new Date('2024-03-01'),
    createdBy: '1',
    evidenceDocuments: [],
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: '1',
    productId: '1',
    name: 'Q1 2024 HCP Education Campaign',
    objective: 'Increase awareness of dosing guidelines',
    status: 'ACTIVE',
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-03-31'),
    taxonomy: {
      channel: 'Email',
      audience: 'Cardiologists',
      region: 'UK',
    },
    linkedClaimIds: ['1', '2'],
    createdBy: '1',
  },
  {
    id: '2',
    productId: '1',
    name: 'Patient Support Programme Launch',
    objective: 'Drive patient enrollment',
    status: 'READY',
    startDate: new Date('2024-02-15'),
    endDate: new Date('2024-06-30'),
    taxonomy: {
      channel: 'Multi-channel',
      audience: 'Patients',
      region: 'EU',
    },
    linkedClaimIds: ['1'],
    createdBy: '1',
  },
  {
    id: '3',
    productId: '3',
    name: 'MS Awareness Month Campaign',
    objective: 'Disease awareness',
    status: 'DRAFT',
    startDate: new Date('2024-05-01'),
    endDate: new Date('2024-05-31'),
    taxonomy: {
      channel: 'Social Media',
      audience: 'General Public',
      region: 'UK',
    },
    linkedClaimIds: [],
    createdBy: '1',
  },
  {
    id: '4',
    productId: '2',
    name: 'Q4 2023 GP Education',
    objective: 'Product positioning',
    status: 'PAUSED',
    startDate: new Date('2023-10-01'),
    endDate: new Date('2023-12-31'),
    taxonomy: {
      channel: 'Webinar',
      audience: 'GPs',
      region: 'UK',
    },
    linkedClaimIds: ['1'],
    createdBy: '1',
  },
];

export const mockMLRCases: MLRCase[] = [
  {
    id: '1',
    campaignId: '1',
    status: 'APPROVED',
    assignedReviewerId: '2',
    submittedAt: new Date('2023-12-15'),
    decidedAt: new Date('2023-12-20'),
    notes: 'All claims properly referenced. Approved for activation.',
    comments: [
      {
        id: '1',
        caseId: '1',
        authorId: '1',
        authorName: 'Dr Sarah Johnson',
        content: 'Submitted for review. All evidence attached.',
        createdAt: new Date('2023-12-15'),
      },
      {
        id: '2',
        caseId: '1',
        authorId: '2',
        authorName: 'Dr Michael Chen',
        content: 'Reviewed. Claims are substantiated. Approved.',
        section: 'Overall',
        createdAt: new Date('2023-12-20'),
      },
    ],
  },
  {
    id: '2',
    campaignId: '2',
    status: 'IN_REVIEW',
    assignedReviewerId: '2',
    submittedAt: new Date('2024-02-01'),
    notes: 'Awaiting reviewer decision.',
    comments: [
      {
        id: '3',
        caseId: '2',
        authorId: '1',
        authorName: 'Dr Sarah Johnson',
        content: 'Submitted for MLR approval.',
        createdAt: new Date('2024-02-01'),
      },
    ],
  },
  {
    id: '3',
    campaignId: '3',
    status: 'DRAFT',
    notes: 'Not yet submitted.',
    comments: [],
  },
];

export const mockSegments: Segment[] = [
  {
    id: '1',
    name: 'Retina Specialists - High Volume',
    description: 'Retina specialists performing 20+ anti-VEGF injections per month',
    query: {
      specialty: 'Retina',
      procedureVolume: { min: 20, procedure: 'Anti-VEGF Injection' },
    },
    segmentType: 'DEMOGRAPHIC',
    estimatedCount: 1245,
    createdBy: '1',
  },
  {
    id: '2',
    name: 'Academic Medical Centers - Tier 1',
    description: 'Major academic medical centers with retina fellowship programs',
    query: {
      institutionType: 'Academic Medical Center',
      tier: 1,
      hasFellowshipProgram: true,
      specialty: 'Ophthalmology',
    },
    segmentType: 'INSTITUTIONAL',
    estimatedCount: 87,
    createdBy: '1',
  },
  {
    id: '3',
    name: 'Recent Wet AMD Prescribers',
    description: 'Ophthalmologists who prescribed anti-VEGF for wet AMD in last 90 days',
    query: {
      lastPrescription: { days: 90, indication: 'Wet AMD' },
    },
    segmentType: 'BEHAVIOURAL',
    estimatedCount: 3420,
    createdBy: '1',
  },
  {
    id: '4',
    name: 'Comprehensive Ophthalmologists',
    description: 'General ophthalmologists managing diabetic eye disease',
    query: {
      specialty: 'Comprehensive Ophthalmology',
      practiceFocus: 'Diabetic Eye Disease',
    },
    segmentType: 'DEMOGRAPHIC',
    estimatedCount: 5680,
    createdBy: '1',
  },
  {
    id: '5',
    name: 'DME-Focused Specialists',
    description: 'Retina specialists with high DME patient volume',
    query: {
      specialty: 'Retina',
      diagnosisVolume: { min: 15, diagnosis: 'Diabetic Macular Edema' },
    },
    segmentType: 'DEMOGRAPHIC',
    estimatedCount: 892,
    createdBy: '1',
  },
  {
    id: '6',
    name: 'Optometrists - Referral Partners',
    description: 'Optometrists who refer retinal cases to specialists',
    query: {
      profession: 'Optometry',
      referralVolume: { min: 10 },
    },
    segmentType: 'DEMOGRAPHIC',
    estimatedCount: 12450,
    createdBy: '1',
  },
  // PATIENT SEGMENTS
  {
    id: '7',
    name: 'Wet AMD Patients - Newly Diagnosed',
    description: 'Patients diagnosed with wet AMD in last 60 days, not yet on treatment',
    query: {
      diagnosis: 'Wet AMD',
      daysSinceDiagnosis: { max: 60 },
      onTreatment: false,
    },
    segmentType: 'BEHAVIOURAL',
    estimatedCount: 8420,
    createdBy: '1',
  },
  {
    id: '8',
    name: 'DME Patients - Active Treatment',
    description: 'Diabetic macular edema patients currently receiving anti-VEGF injections',
    query: {
      diagnosis: 'Diabetic Macular Edema',
      onTreatment: true,
      lastInjection: { days: 90 },
    },
    segmentType: 'BEHAVIOURAL',
    estimatedCount: 15680,
    createdBy: '1',
  },
  {
    id: '9',
    name: 'Diabetic Retinopathy - Pre-DME',
    description: 'Diabetic patients with retinopathy at risk for progression to DME',
    query: {
      diagnosis: 'Diabetic Retinopathy',
      severity: ['Moderate', 'Severe'],
      hasDME: false,
    },
    segmentType: 'DEMOGRAPHIC',
    estimatedCount: 22340,
    createdBy: '1',
  },
  {
    id: '10',
    name: 'AMD Caregivers & Family Members',
    description: 'Family members and caregivers of patients with wet AMD',
    query: {
      relationship: 'Caregiver',
      patientDiagnosis: 'Wet AMD',
      activelyInvolved: true,
    },
    segmentType: 'DEMOGRAPHIC',
    estimatedCount: 6890,
    createdBy: '1',
  },
  {
    id: '11',
    name: 'Treatment Non-Adherent Patients',
    description: 'Patients who have missed 2+ scheduled injection appointments',
    query: {
      onTreatment: true,
      missedAppointments: { min: 2 },
      lastContact: { days: 120 },
    },
    segmentType: 'BEHAVIOURAL',
    estimatedCount: 4230,
    createdBy: '1',
  },
];

export const mockDashboard: Dashboard = {
  totalCampaigns: 4,
  activeCampaigns: 1,
  pendingMLR: 1,
  approvedClaims: 2,
  recentEvents: 12847,
};

// Mock Content Library - 80+ ophthalmology assets for demonstration
import type { ContentAsset } from '@/types';

export const mockContentLibrary: ContentAsset[] = [
  // ===================
  // EYLEA EMAIL CONTENT
  // ===================
  {
    id: 'CNT-2024-0001',
    title: 'Eylea Wet AMD: HAWK Study Results',
    description: 'HCP email showcasing Eylea efficacy data from HAWK trial for retina specialists',
    assetType: 'EMAIL_TEMPLATE',
    channel: 'EMAIL',
    brandId: '1', // Eylea
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    mlrCaseId: 'MLR-023',
    thumbnailUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400&h=300&fit=crop',
    tags: ['HCP', 'Retina', 'Wet AMD', 'Clinical Data', 'HAWK'],
    audienceType: 'HCP',
    version: 2,
    effectiveFrom: new Date('2024-01-15'),
    createdBy: '1',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'CNT-2024-0002',
    title: 'Eylea DME: VISTA and VIVID Durability',
    description: 'Long-term durability data from VISTA/VIVID trials for DME indication',
    assetType: 'EMAIL_HTML',
    channel: 'EMAIL',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400',
    tags: ['HCP', 'DME', 'Durability', 'VISTA', 'VIVID'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-01-20'),
    createdBy: '1',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'CNT-2024-0003',
    title: 'Eylea Q8 Dosing: Treat and Extend Protocol',
    description: 'Dosing flexibility with Q8 maintenance for stable wet AMD patients',
    assetType: 'EMAIL_TEMPLATE',
    channel: 'EMAIL',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=400',
    tags: ['HCP', 'Dosing', 'Q8', 'Treat and Extend'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-02-01'),
    createdBy: '1',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'CNT-2024-0004',
    title: 'Eylea RVO: Real-World Evidence',
    description: 'Post-marketing data for retinal vein occlusion treatment outcomes',
    assetType: 'EMAIL_TEMPLATE',
    channel: 'EMAIL',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1631217877000-6f4b1e21e8f7?w=400',
    tags: ['HCP', 'RVO', 'Real-World Evidence', 'Outcomes'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-02-05'),
    createdBy: '1',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-05'),
  },

  // ==================
  // EYLEA WEB CONTENT
  // ==================
  {
    id: 'CNT-2024-0010',
    title: 'Eylea HCP Portal: Clinical Data Hub',
    description: 'Main HCP landing page with HAWK, HARRIER, VISTA, VIVID trial data',
    assetType: 'WEB_LANDING_PAGE',
    channel: 'WEB',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    mlrCaseId: 'MLR-021',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400',
    tags: ['HCP', 'Portal', 'Clinical Trials', 'Multi-Indication'],
    audienceType: 'HCP',
    version: 3,
    effectiveFrom: new Date('2024-01-10'),
    createdBy: '1',
    createdAt: new Date('2023-12-15'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'CNT-2024-0005',
    title: 'Eylea Clinical Study Banner',
    description: 'Web banner highlighting latest clinical study results',
    assetType: 'WEB_BANNER',
    channel: 'WEB',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400',
    tags: ['HCP', 'Clinical Study', 'Banner'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-02-15'),
    createdBy: '1',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-15'),
  },
  //===============================
  // EYLEA PAID SOCIAL (LinkedIn)
  //===============================
  {
    id: 'CNT-2024-0011',
    title: 'Eylea LinkedIn: Thought Leadership - Anti-VEGF Paradigms',
    description: 'LinkedIn sponsored post targeting retina specialists on treatment approaches',
    assetType: 'PAID_SOCIAL_AD',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400',
    tags: ['HCP', 'LinkedIn', 'Thought Leadership', 'Retina Specialists'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-02-10'),
    createdBy: '1',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'CNT-2024-0012',
    title: 'Eylea LinkedIn: HAWK Study Infographic',
    description: 'Carousel ad with HAWK trial results for wet AMD',
    assetType: 'PAID_SOCIAL_AD',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400',
    tags: ['HCP', 'LinkedIn', 'HAWK', 'Infographic', 'Wet AMD'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-02-15'),
    createdBy: '1',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-15'),
  },

  //=========================
  // EYLEA PAID SEARCH (Google Ads)
  //=========================
  {
    id: 'CNT-2024-0020',
    title: 'Eylea Google Ads: "wet AMD treatment" - Search Campaign',
    description: 'Search ad targeting "wet AMD treatment efficacy" and related keywords',
    assetType: 'PAID_SEARCH_AD',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?w=400',
    tags: ['HCP', 'Google Ads', 'Wet AMD', 'Search'],
    audienceType: 'HCP',
    version: 2,
    effectiveFrom: new Date('2024-02-20'),
    createdBy: '1',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: 'CNT-2024-0021',
    title: 'Eylea Google Ads: "DME injection treatment" - Search Campaign',
    description: 'Search ad targeting DME-related physician searches',
    assetType: 'PAID_SEARCH_AD',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1523961131990-5ea7c61b2107?w=400',
    tags: ['HCP', 'Google Ads', 'DME', 'Search'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-02-25'),
    createdBy: '1',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-25'),
  },

  //===================================
  // EYLEA PAID DISPLAY (Programmatic)
  //===================================
  {
    id: 'CNT-2024-0030',
    title: 'Eylea Medscape Banner: AMD Clinical Update',
    description: 'Programmatic display banner on Medscape targeting ophthalmologists',
    assetType: 'PAID_DISPLAY_AD',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551836022-4c4c79ecde51?w=400',
    tags: ['HCP', 'Display', 'Medscape', 'AMD'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-03-01'),
    createdBy: '1',
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'CNT-2024-0031',
    title: 'Eylea AAO.org Banner: Multi-Indication Overview',
    description: 'Display ad on American Academy of Ophthalmology website',
    assetType: 'PAID_DISPLAY_AD',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400',
    tags: ['HCP', 'Display', 'AAO', 'Multi-Indication'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-03-05'),
    createdBy: '1',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-05'),
  },

  //===============================
  // EYLEA PRINT (Medical Journals)
  //===============================
  {
    id: 'CNT-2024-0040',
    title: 'Eylea Full Page Ad: Retina Times - Durability Data',
    description: 'Full-page journal ad in Retina Times featuring long-term durability',
    assetType: 'PRINT_JOURNAL_AD',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=400',
    tags: ['HCP', 'Print', 'Retina Times', 'Durability'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-03-10'),
    createdBy: '1',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-10'),
  },
  {
    id: 'CNT-2024-0041',
    title: 'Eylea Insert: Ophthalmology Journal - Q8 Dosing',
    description: 'Journal insert highlighting Q8 dosing flexibility',
    assetType: 'PRINT_JOURNAL_AD',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400',
    tags: ['HCP', 'Print', 'Ophthalmology', 'Q8 Dosing'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-03-15'),
    createdBy: '1',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'CNT-2024-0042',
    title: 'Eylea JAMA Ophthalmology Ad: Real-World Evidence',
    description: 'Half-page ad in JAMA Ophthalmology with post-marketing data',
    assetType: 'PRINT_JOURNAL_AD',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=400',
    tags: ['HCP', 'Print', 'JAMA Ophthalmology', 'RWE'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-03-20'),
    createdBy: '1',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-20'),
  },

  //===========================
  // EYLEA TV/RADIO (DTC - Rare)
  //===========================
  {
    id: 'CNT-2024-0050',
    title: 'Eylea TV Spot: Wet AMD Awareness (30 sec)',
    description: 'DTC television commercial for wet AMD patient awareness',
    assetType: 'TV_SPOT',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=400',
    tags: ['PATIENT', 'TV', 'DTC', 'Wet AMD', 'Awareness'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-03-25'),
    createdBy: '1',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-25'),
  },

  //===================================
  // EYLEA OUT-OF-HOME (Conference/Airport)
  //===================================
  {
    id: 'CNT-2024-0060',
    title: 'Eylea AAO Conference Banner: Booth Signage',
    description: 'Large-format banner for AAO Annual Meeting booth',
    assetType: 'OOH_CREATIVE',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400',
    tags: ['HCP', 'OOH', 'AAO Conference', 'Event'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-04-01'),
    createdBy: '1',
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-04-01'),
  },
  {
    id: 'CNT-2024-0061',
    title: 'Eylea Airport Ad: San Francisco Terminal - AAO',
    description: 'Digital billboard at SFO airport during AAO Annual Meeting week',
    assetType: 'OOH_CREATIVE',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=400',
    tags: ['HCP', 'OOH', 'Airport', 'AAO', 'Digital Billboard'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-04-05'),
    createdBy: '1',
    createdAt: new Date('2024-03-25'),
    updatedAt: new Date('2024-04-05'),
  },

  //================================
  // LUCENTIS EMAIL CONTENT
  //================================
  {
    id: 'CNT-2024-0100',
    title: 'Lucentis Wet AMD: PIER Study Long-Term Data',
    description: 'Email highlighting sustained efficacy from PIER trial',
    assetType: 'EMAIL_TEMPLATE',
    channel: 'EMAIL',
    brandId: '2', // Lucentis
    linkedClaimIds: ['2'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=400',
    tags: ['HCP', 'Wet AMD', 'PIER', 'Long-Term'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-04-10'),
    createdBy: '1',
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-04-10'),
  },
  {
    id: 'CNT-2024-0101',
    title: 'Lucentis DME: RIDE/RISE Real-World Follow-Up',
    description: 'Post-marketing outcomes data for DME treatment',
    assetType: 'EMAIL_HTML',
    channel: 'EMAIL',
    brandId: '2',
    linkedClaimIds: ['2'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1576671081837-49000212a370?w=400',
    tags: ['HCP', 'DME', 'RIDE', 'RISE', 'RWE'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-04-15'),
    createdBy: '1',
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-04-15'),
  },

  //============================
  // LUCENTIS PAID SOCIAL
  //============================
  {
    id: 'CNT-2024-0110',
    title: 'Lucentis LinkedIn: Myopic CNV Case Studies',
    description: 'LinkedIn sponsored post with real-world case examples',
    assetType: 'PAID_SOCIAL_AD',
    channel: 'PAID_MEDIA',
    brandId: '2',
    linkedClaimIds: ['2'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400',
    tags: ['HCP', 'LinkedIn', 'Myopic CNV', 'Case Studies'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-04-20'),
    createdBy: '1',
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-04-20'),
  },

  //==========================
  // LUCENTIS PAID SEARCH
  //==========================
  {
    id: 'CNT-2024-0120',
    title: 'Lucentis Google Ads: "anti-VEGF treatment comparison"',
    description: 'Search ad targeting comparative efficacy queries',
    assetType: 'PAID_SEARCH_AD',
    channel: 'PAID_MEDIA',
    brandId: '2',
    linkedClaimIds: ['2'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400',
    tags: ['HCP', 'Google Ads', 'Comparison', 'Anti-VEGF'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-04-25'),
    createdBy: '1',
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-04-25'),
  },

  //============================
  // LUCENTIS PRINT
  //============================
  {
    id: 'CNT-2024-0130',
    title: 'Lucentis Retina Times Ad: Established Efficacy Profile',
    description: 'Full-page ad emphasizing long market history and proven outcomes',
    assetType: 'PRINT_JOURNAL_AD',
    channel: 'PAID_MEDIA',
    brandId: '2',
    linkedClaimIds: ['2'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=400',
    tags: ['HCP', 'Print', 'Retina Times', 'Established Efficacy'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-05-01'),
    createdBy: '1',
    createdAt: new Date('2024-04-25'),
    updatedAt: new Date('2024-05-01'),
  },

  //============================
  // BEOVU EMAIL CONTENT
  //============================
  {
    id: 'CNT-2024-0200',
    title: 'Beovu Wet AMD: HAWK and HARRIER Overview',
    description: 'Email introducing Beovu with pivotal trial data',
    assetType: 'EMAIL_TEMPLATE',
    channel: 'EMAIL',
    brandId: '3', // Beovu
    linkedClaimIds: ['3'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400',
    tags: ['HCP', 'Wet AMD', 'HAWK', 'HARRIER', 'New Product'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-05-05'),
    createdBy: '1',
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-05-05'),
  },
  {
    id: 'CNT-2024-0201',
    title: 'Beovu Safety Update: Latest Post-Marketing Data',
    description: 'Email with updated safety profile and risk management',
    assetType: 'EMAIL_HTML',
    channel: 'EMAIL',
    brandId: '3',
    linkedClaimIds: ['3'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=400',
    tags: ['HCP', 'Safety', 'Post-Marketing', 'Risk Management'],
    audienceType: 'HCP',
    version: 2,
    effectiveFrom: new Date('2024-05-10'),
    createdBy: '1',
    createdAt: new Date('2024-05-05'),
    updatedAt: new Date('2024-05-10'),
  },

  //==========================
  // BEOVU PAID SOCIAL
  //==========================
  {
    id: 'CNT-2024-0210',
    title: 'Beovu LinkedIn: Next-Generation Anti-VEGF',
    description: 'LinkedIn sponsored post positioning Beovu as newer option',
    assetType: 'PAID_SOCIAL_AD',
    channel: 'PAID_MEDIA',
    brandId: '3',
    linkedClaimIds: ['3'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400',
    tags: ['HCP', 'LinkedIn', 'Next-Gen', 'Innovation'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-05-15'),
    createdBy: '1',
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-05-15'),
  },

  //========================
  // BEOVU PRINT
  //========================
  {
    id: 'CNT-2024-0220',
    title: 'Beovu Ophthalmology Journal: HAWK Data Spotlight',
    description: 'Journal ad featuring key HAWK trial endpoints',
    assetType: 'PRINT_JOURNAL_AD',
    channel: 'PAID_MEDIA',
    brandId: '3',
    linkedClaimIds: ['3'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?w=400',
    tags: ['HCP', 'Print', 'Ophthalmology', 'HAWK'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-05-20'),
    createdBy: '1',
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-05-20'),
  },

  //================================
  // MOBILE PUSH (Patient Support)
  //================================
  {
    id: 'CNT-2024-0300',
    title: 'Eylea Mobile: Injection Appointment Reminder',
    description: 'Push notification for upcoming anti-VEGF injection appointment',
    assetType: 'MOBILE_PUSH',
    channel: 'MOBILE',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400',
    tags: ['PATIENT', 'Reminder', 'Adherence', 'Appointment'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-05-25'),
    createdBy: '1',
    createdAt: new Date('2024-05-20'),
    updatedAt: new Date('2024-05-25'),
  },

  //=================================
  // SOCIAL MEDIA (Organic)
  //=================================
  {
    id: 'CNT-2024-0400',
    title: 'Eylea LinkedIn: Retina Specialist Thought Leadership',
    description: 'Organic LinkedIn post from brand account with clinical insights',
    assetType: 'SOCIAL_POST',
    channel: 'SOCIAL',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400',
    tags: ['HCP', 'LinkedIn', 'Thought Leadership', 'Organic'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-06-01'),
    createdBy: '1',
    createdAt: new Date('2024-05-28'),
    updatedAt: new Date('2024-06-01'),
  },

  //===================================
  // PATIENT EMAIL CONTENT
  //===================================
  {
    id: 'CNT-2024-0500',
    title: 'Eylea Patient Welcome: Understanding Wet AMD',
    description: 'Welcome email for newly diagnosed wet AMD patients with treatment overview',
    assetType: 'EMAIL_TEMPLATE',
    channel: 'EMAIL',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=400',
    tags: ['PATIENT', 'Welcome', 'Wet AMD', 'Education'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-06-05'),
    createdBy: '1',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-05'),
  },
  {
    id: 'CNT-2024-0501',
    title: 'Eylea Injection Prep: What to Expect',
    description: 'Pre-injection preparation email with appointment details and what to bring',
    assetType: 'EMAIL_HTML',
    channel: 'EMAIL',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400',
    tags: ['PATIENT', 'Injection', 'Preparation', 'Instructions'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-06-10'),
    createdBy: '1',
    createdAt: new Date('2024-06-08'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'CNT-2024-0502',
    title: 'DME Patient Support: Managing Diabetes & Vision',
    description: 'Educational email connecting diabetes management with eye health',
    assetType: 'EMAIL_TEMPLATE',
    channel: 'EMAIL',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1576671081837-49000212a370?w=400',
    tags: ['PATIENT', 'DME', 'Diabetes', 'Lifestyle'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-06-15'),
    createdBy: '1',
    createdAt: new Date('2024-06-12'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'CNT-2024-0503',
    title: 'Lucentis Patient Success Stories',
    description: 'Real patient testimonials and treatment journey stories',
    assetType: 'EMAIL_HTML',
    channel: 'EMAIL',
    brandId: '2',
    linkedClaimIds: ['2'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=400',
    tags: ['PATIENT', 'Testimonials', 'Success Stories', 'Engagement'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-06-20'),
    createdBy: '1',
    createdAt: new Date('2024-06-18'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'CNT-2024-0504',
    title: 'Appointment Reminder: Injection Due Soon',
    description: 'Automated reminder 1 week before scheduled injection appointment',
    assetType: 'EMAIL_TEMPLATE',
    channel: 'EMAIL',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=400',
    tags: ['PATIENT', 'Reminder', 'Appointment', 'Adherence'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-06-25'),
    createdBy: '1',
    createdAt: new Date('2024-06-22'),
    updatedAt: new Date('2024-06-25'),
  },
  {
    id: 'CNT-2024-0505',
    title: 'Caregiver Guide: Supporting AMD Patients',
    description: 'Email for caregivers with tips for supporting loved ones with vision loss',
    assetType: 'EMAIL_HTML',
    channel: 'EMAIL',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?w=400',
    tags: ['PATIENT', 'Caregiver', 'Support', 'Education'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-07-01'),
    createdBy: '1',
    createdAt: new Date('2024-06-28'),
    updatedAt: new Date('2024-07-01'),
  },

  //===================================
  // PATIENT WEB CONTENT
  //===================================
  {
    id: 'CNT-2024-0510',
    title: 'Eylea Patient Portal: My Treatment Journey',
    description: 'Patient portal landing page with injection history and upcoming appointments',
    assetType: 'WEB_LANDING_PAGE',
    channel: 'WEB',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400',
    tags: ['PATIENT', 'Portal', 'Treatment Tracking', 'Dashboard'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-07-05'),
    createdBy: '1',
    createdAt: new Date('2024-07-01'),
    updatedAt: new Date('2024-07-05'),
  },
  {
    id: 'CNT-2024-0511',
    title: 'Understanding Wet AMD: Symptoms & Treatment',
    description: 'Educational web article explaining wet AMD causes and treatment options',
    assetType: 'WEB_ARTICLE',
    channel: 'WEB',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=400',
    tags: ['PATIENT', 'Education', 'Wet AMD', 'Symptoms'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-07-10'),
    createdBy: '1',
    createdAt: new Date('2024-07-08'),
    updatedAt: new Date('2024-07-10'),
  },
  {
    id: 'CNT-2024-0512',
    title: 'Financial Assistance Programs Banner',
    description: 'Web banner promoting copay assistance and patient support programs',
    assetType: 'WEB_BANNER',
    channel: 'WEB',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1633158829875-e5316a358c6f?w=400',
    tags: ['PATIENT', 'Financial Assistance', 'Support Programs', 'Copay'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-07-15'),
    createdBy: '1',
    createdAt: new Date('2024-07-12'),
    updatedAt: new Date('2024-07-15'),
  },
  {
    id: 'CNT-2024-0513',
    title: 'Lucentis FAQs: Common Patient Questions',
    description: 'Comprehensive FAQ page addressing treatment concerns and side effects',
    assetType: 'WEB_ARTICLE',
    channel: 'WEB',
    brandId: '2',
    linkedClaimIds: ['2'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=400',
    tags: ['PATIENT', 'FAQ', 'Questions', 'Education'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-07-20'),
    createdBy: '1',
    createdAt: new Date('2024-07-18'),
    updatedAt: new Date('2024-07-20'),
  },

  //===================================
  // PATIENT MOBILE CONTENT
  //===================================
  {
    id: 'CNT-2024-0520',
    title: 'Push: Appointment Tomorrow',
    description: 'Push notification 24 hours before injection appointment',
    assetType: 'MOBILE_PUSH',
    channel: 'MOBILE',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400',
    tags: ['PATIENT', 'Push', 'Appointment', 'Reminder'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-07-25'),
    createdBy: '1',
    createdAt: new Date('2024-07-22'),
    updatedAt: new Date('2024-07-25'),
  },
  {
    id: 'CNT-2024-0521',
    title: 'App Message: Post-Injection Care Tips',
    description: 'In-app message with care instructions after injection procedure',
    assetType: 'MOBILE_IN_APP',
    channel: 'MOBILE',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=400',
    tags: ['PATIENT', 'In-App', 'Post-Injection', 'Care'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-08-01'),
    createdBy: '1',
    createdAt: new Date('2024-07-28'),
    updatedAt: new Date('2024-08-01'),
  },
  {
    id: 'CNT-2024-0522',
    title: 'Push: Vision Symptom Tracker Reminder',
    description: 'Weekly reminder to log vision symptoms in patient app',
    assetType: 'MOBILE_PUSH',
    channel: 'MOBILE',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?w=400',
    tags: ['PATIENT', 'Symptom Tracking', 'Engagement', 'Reminder'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-08-05'),
    createdBy: '1',
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2024-08-05'),
  },

  //===================================
  // MORE HCP WEB CONTENT
  //===================================
  {
    id: 'CNT-2024-0530',
    title: 'Eylea Dosing Calculator Tool',
    description: 'Interactive web tool for calculating individualized dosing schedules',
    assetType: 'WEB_LANDING_PAGE',
    channel: 'WEB',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400',
    tags: ['HCP', 'Tool', 'Dosing', 'Calculator'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-08-10'),
    createdBy: '1',
    createdAt: new Date('2024-08-08'),
    updatedAt: new Date('2024-08-10'),
  },
  {
    id: 'CNT-2024-0531',
    title: 'Lucentis CME Module: Advanced AMD Management',
    description: 'Continuing medical education web module with certification',
    assetType: 'WEB_ARTICLE',
    channel: 'WEB',
    brandId: '2',
    linkedClaimIds: ['2'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=400',
    tags: ['HCP', 'CME', 'Education', 'Certification'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-08-15'),
    createdBy: '1',
    createdAt: new Date('2024-08-12'),
    updatedAt: new Date('2024-08-15'),
  },
  {
    id: 'CNT-2024-0532',
    title: 'Beovu Safety Monitoring Resources',
    description: 'Web resource center with safety monitoring protocols and reporting',
    assetType: 'WEB_LANDING_PAGE',
    channel: 'WEB',
    brandId: '3',
    linkedClaimIds: ['3'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400',
    tags: ['HCP', 'Safety', 'Monitoring', 'Resources'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-08-20'),
    createdBy: '1',
    createdAt: new Date('2024-08-18'),
    updatedAt: new Date('2024-08-20'),
  },

  //===================================
  // MORE HCP MOBILE & SOCIAL
  //===================================
  {
    id: 'CNT-2024-0540',
    title: 'HCP App: New Clinical Data Alert',
    description: 'Push notification for breaking clinical trial results',
    assetType: 'MOBILE_PUSH',
    channel: 'MOBILE',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400',
    tags: ['HCP', 'Clinical Data', 'Alert', 'Push'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-08-25'),
    createdBy: '1',
    createdAt: new Date('2024-08-22'),
    updatedAt: new Date('2024-08-25'),
  },
  {
    id: 'CNT-2024-0541',
    title: 'LinkedIn: AAO Conference Highlights',
    description: 'Social post series from American Academy of Ophthalmology meeting',
    assetType: 'SOCIAL_POST',
    channel: 'SOCIAL',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400',
    tags: ['HCP', 'Conference', 'AAO', 'LinkedIn'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-09-01'),
    createdBy: '1',
    createdAt: new Date('2024-08-28'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: 'CNT-2024-0542',
    title: 'Twitter: Weekly Retina Research Roundup',
    description: 'Weekly summary of latest retina research publications',
    assetType: 'SOCIAL_POST',
    channel: 'SOCIAL',
    brandId: '2',
    linkedClaimIds: ['2'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400',
    tags: ['HCP', 'Research', 'Twitter', 'Weekly'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-09-05'),
    createdBy: '1',
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-09-05'),
  },

  //===================================
  // VIDEO CONTENT
  //===================================
  {
    id: 'CNT-2024-0550',
    title: 'Eylea Injection Technique Video',
    description: '5-minute video demonstrating proper intravitreal injection technique',
    assetType: 'VIDEO',
    channel: 'WEB',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1492619375914-88005aa9e8fb?w=400',
    tags: ['HCP', 'Video', 'Injection', 'Technique'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-09-10'),
    createdBy: '1',
    createdAt: new Date('2024-09-05'),
    updatedAt: new Date('2024-09-10'),
  },
  {
    id: 'CNT-2024-0551',
    title: 'Patient Story: Living with Wet AMD',
    description: '3-minute patient testimonial video about treatment experience',
    assetType: 'VIDEO',
    channel: 'WEB',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400',
    tags: ['PATIENT', 'Video', 'Testimonial', 'Story'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-09-15'),
    createdBy: '1',
    createdAt: new Date('2024-09-10'),
    updatedAt: new Date('2024-09-15'),
  },
  {
    id: 'CNT-2024-0552',
    title: 'HAWK Study Results Animation',
    description: 'Animated explainer video of HAWK trial methodology and results',
    assetType: 'VIDEO',
    channel: 'WEB',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?w=400',
    tags: ['HCP', 'Video', 'HAWK', 'Clinical Data'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-09-20'),
    createdBy: '1',
    createdAt: new Date('2024-09-15'),
    updatedAt: new Date('2024-09-20'),
  },

  //===================================
  // ADDITIONAL PAID MEDIA
  //===================================
  {
    id: 'CNT-2024-0560',
    title: 'Facebook Ad: Caregiver Support Group',
    description: 'Paid Facebook ad promoting online caregiver community',
    assetType: 'PAID_SOCIAL_AD',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400',
    tags: ['PATIENT', 'Facebook', 'Caregiver', 'Community'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-09-25'),
    createdBy: '1',
    createdAt: new Date('2024-09-20'),
    updatedAt: new Date('2024-09-25'),
  },
  {
    id: 'CNT-2024-0561',
    title: 'Google Display: Patient Education Series',
    description: 'Display ad series on health websites targeting AMD patients',
    assetType: 'PAID_DISPLAY_AD',
    channel: 'PAID_MEDIA',
    brandId: '2',
    linkedClaimIds: ['2'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400',
    tags: ['PATIENT', 'Display', 'Education', 'Health Sites'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-10-01'),
    createdBy: '1',
    createdAt: new Date('2024-09-28'),
    updatedAt: new Date('2024-10-01'),
  },
  {
    id: 'CNT-2024-0562',
    title: 'Radio Spot: AMD Awareness Month',
    description: '30-second radio commercial for Age-Related Macular Degeneration awareness',
    assetType: 'RADIO_SPOT',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=400',
    tags: ['PATIENT', 'Radio', 'DTC', 'Awareness'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-10-05'),
    createdBy: '1',
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-10-05'),
  },

  //===================================
  // PATIENT SOCIAL MEDIA (Fill gap)
  //===================================
  {
    id: 'CNT-2024-0600',
    title: 'Facebook: Living Well with AMD Community',
    description: 'Organic Facebook post promoting patient community and support',
    assetType: 'SOCIAL_POST',
    channel: 'SOCIAL',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400',
    tags: ['PATIENT', 'Facebook', 'Community', 'Support'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-10-10'),
    createdBy: '1',
    createdAt: new Date('2024-10-08'),
    updatedAt: new Date('2024-10-10'),
  },
  {
    id: 'CNT-2024-0601',
    title: 'Instagram: Patient Success Story Visual',
    description: 'Instagram post with patient testimonial and treatment journey infographic',
    assetType: 'SOCIAL_POST',
    channel: 'SOCIAL',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=400',
    tags: ['PATIENT', 'Instagram', 'Visual', 'Testimonial'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-10-15'),
    createdBy: '1',
    createdAt: new Date('2024-10-12'),
    updatedAt: new Date('2024-10-15'),
  },

  //===================================
  // MORE PATIENT PAID MEDIA (Fill gaps)
  //===================================
  {
    id: 'CNT-2024-0610',
    title: 'Facebook Ad: Free AMD Screening',
    description: 'Paid Facebook ad promoting free AMD screening events',
    assetType: 'PAID_SOCIAL_AD',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400',
    tags: ['PATIENT', 'Facebook', 'Screening', 'Event'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-10-20'),
    createdBy: '1',
    createdAt: new Date('2024-10-18'),
    updatedAt: new Date('2024-10-20'),
  },
  {
    id: 'CNT-2024-0611',
    title: 'Google Search: "wet AMD treatment options"',
    description: 'Paid search ad targeting patients searching for AMD treatment information',
    assetType: 'PAID_SEARCH_AD',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?w=400',
    tags: ['PATIENT', 'Google Ads', 'Search', 'Treatment'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-10-25'),
    createdBy: '1',
    createdAt: new Date('2024-10-22'),
    updatedAt: new Date('2024-10-25'),
  },
  {
    id: 'CNT-2024-0612',
    title: 'TV Spot: Eylea "See What Matters" 60sec',
    description: 'Extended DTC television spot featuring patient stories and treatment journey',
    assetType: 'TV_SPOT',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=400',
    tags: ['PATIENT', 'TV', 'DTC', 'Brand Campaign'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-11-01'),
    createdBy: '1',
    createdAt: new Date('2024-10-25'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: 'CNT-2024-0613',
    title: 'Lucentis Display Banner: Diabetic Eye Health',
    description: 'Paid display banner on diabetes-focused health websites',
    assetType: 'PAID_DISPLAY_AD',
    channel: 'PAID_MEDIA',
    brandId: '2',
    linkedClaimIds: ['2'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400',
    tags: ['PATIENT', 'Display', 'Diabetes', 'DME'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-11-05'),
    createdBy: '1',
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-11-05'),
  },

  //===================================
  // GENERIC "FALLBACK" CONTENT (Always available)
  //===================================
  {
    id: 'CNT-2024-0900',
    title: '[TEMPLATE] General HCP Email',
    description: 'Generic HCP email template - customizable for any campaign',
    assetType: 'EMAIL_TEMPLATE',
    channel: 'EMAIL',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400',
    tags: ['HCP', 'Template', 'Generic'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-01-01'),
    createdBy: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'CNT-2024-0901',
    title: '[TEMPLATE] General Patient Email',
    description: 'Generic patient email template - customizable for any campaign',
    assetType: 'EMAIL_TEMPLATE',
    channel: 'EMAIL',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=400',
    tags: ['PATIENT', 'Template', 'Generic'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-01-01'),
    createdBy: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'CNT-2024-0902',
    title: '[TEMPLATE] General Web Landing Page',
    description: 'Generic web landing page template - customizable for any audience',
    assetType: 'WEB_LANDING_PAGE',
    channel: 'WEB',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400',
    tags: ['HCP', 'PATIENT', 'Template', 'Generic'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-01-01'),
    createdBy: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'CNT-2024-0903',
    title: '[TEMPLATE] General Mobile Push',
    description: 'Generic mobile push notification template',
    assetType: 'MOBILE_PUSH',
    channel: 'MOBILE',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400',
    tags: ['PATIENT', 'Template', 'Generic'],
    audienceType: 'PATIENT',
    version: 1,
    effectiveFrom: new Date('2024-01-01'),
    createdBy: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'CNT-2024-0904',
    title: '[TEMPLATE] General Social Post',
    description: 'Generic social media post template for any platform',
    assetType: 'SOCIAL_POST',
    channel: 'SOCIAL',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400',
    tags: ['HCP', 'PATIENT', 'Template', 'Generic'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-01-01'),
    createdBy: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'CNT-2024-0905',
    title: '[TEMPLATE] General Paid Social Ad',
    description: 'Generic paid social ad template for LinkedIn/Facebook',
    assetType: 'PAID_SOCIAL_AD',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400',
    tags: ['HCP', 'PATIENT', 'Template', 'Generic'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-01-01'),
    createdBy: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'CNT-2024-0906',
    title: '[TEMPLATE] General Paid Search Ad',
    description: 'Generic paid search ad template for Google Ads',
    assetType: 'PAID_SEARCH_AD',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?w=400',
    tags: ['HCP', 'PATIENT', 'Template', 'Generic'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-01-01'),
    createdBy: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'CNT-2024-0907',
    title: '[TEMPLATE] General Display Ad',
    description: 'Generic display ad template for programmatic campaigns',
    assetType: 'PAID_DISPLAY_AD',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400',
    tags: ['HCP', 'PATIENT', 'Template', 'Generic'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-01-01'),
    createdBy: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'CNT-2024-0908',
    title: '[TEMPLATE] General Print Ad',
    description: 'Generic print ad template for journals and magazines',
    assetType: 'PRINT_AD',
    channel: 'PAID_MEDIA',
    brandId: '1',
    linkedClaimIds: ['1'],
    mlrStatus: 'APPROVED',
    thumbnailUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=400',
    tags: ['HCP', 'Template', 'Generic'],
    audienceType: 'HCP',
    version: 1,
    effectiveFrom: new Date('2024-01-01'),
    createdBy: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

// Microsegments - Based on Segment ID '1' (Retina Specialists - High Volume)
export const mockMicrosegments: Microsegment[] = [
  {
    id: 'MSEG-001',
    parentSegmentId: '1',
    name: 'High Engagers - Urban Academic Centers',
    description: 'Top 25% engagement, urban academic medical centers, high prescription volume',
    criteria: {
      demographics: {
        region: ['Northeast', 'West Coast', 'Mid-Atlantic'],
      },
      behavioral: {
        engagementScore: { min: 75, max: 100 },
        previousCampaignResponse: 'HIGH',
        channelPreference: ['EMAIL', 'WEB'],
      },
      institutional: {
        practiceSetting: ['Academic Medical Center'],
        volumeCategory: 'HIGH',
        tier: 1,
      },
    },
    estimatedCount: 312,
    autoGenerated: true,
    isActive: true,
    createdAt: new Date('2024-11-01'),
  },
  {
    id: 'MSEG-002',
    parentSegmentId: '1',
    name: 'Medium Engagers - Private Practice',
    description: 'Mid-tier engagement, private practice settings, moderate volume',
    criteria: {
      demographics: {
        region: ['Southeast', 'Midwest', 'Southwest'],
      },
      behavioral: {
        engagementScore: { min: 50, max: 74 },
        previousCampaignResponse: 'MEDIUM',
        channelPreference: ['EMAIL', 'PAID_MEDIA'],
      },
      institutional: {
        practiceSetting: ['Private Practice', 'Group Practice'],
        volumeCategory: 'MEDIUM',
        tier: 2,
      },
    },
    estimatedCount: 436,
    autoGenerated: true,
    isActive: true,
    createdAt: new Date('2024-11-01'),
  },
  {
    id: 'MSEG-003',
    parentSegmentId: '1',
    name: 'Low Engagers - Rural Community',
    description: 'Lower engagement, rural/community settings, lower prescription volume',
    criteria: {
      demographics: {
        region: ['Mountain', 'Plains', 'Rural'],
      },
      behavioral: {
        engagementScore: { min: 0, max: 49 },
        previousCampaignResponse: 'LOW',
        channelPreference: ['PAID_MEDIA'],
      },
      institutional: {
        practiceSetting: ['Community Hospital', 'Rural Clinic'],
        volumeCategory: 'LOW',
        tier: 3,
      },
    },
    estimatedCount: 311,
    autoGenerated: true,
    isActive: true,
    createdAt: new Date('2024-11-01'),
  },
  {
    id: 'MSEG-004',
    parentSegmentId: '1',
    name: 'New to Brand - High Volume',
    description: 'Never interacted with brand, but high prescription volume potential',
    criteria: {
      behavioral: {
        lastInteractionDays: 999, // Never interacted
        channelPreference: ['EMAIL', 'PAID_MEDIA', 'WEB'],
      },
      institutional: {
        volumeCategory: 'HIGH',
        tier: 1,
      },
    },
    estimatedCount: 186,
    autoGenerated: true,
    isActive: true,
    createdAt: new Date('2024-11-01'),
  },
];

// Content Resonance Predictions
export const mockContentResonance: ContentResonancePrediction[] = [
  // CNT-2024-0001 (HAWK Study Email) predictions for all microsegments
  {
    contentId: 'CNT-2024-0001',
    microsegmentId: 'MSEG-001',
    resonanceScore: 92,
    historicalData: [
      {
        campaignId: 'CMP-2024-Q3-001',
        openRate: 0.89,
        clickRate: 0.42,
        conversionRate: 0.23,
        sampleSize: 287,
      },
      {
        campaignId: 'CMP-2024-Q2-003',
        openRate: 0.91,
        clickRate: 0.45,
        conversionRate: 0.28,
        sampleSize: 312,
      },
      {
        campaignId: 'CMP-2024-Q1-005',
        openRate: 0.88,
        clickRate: 0.40,
        conversionRate: 0.21,
        sampleSize: 295,
      },
    ],
    predictedMetrics: {
      openRate: 0.90,
      clickRate: 0.44,
      conversionRate: 0.26,
      confidence: 0.85,
    },
    recommendations: [
      'Best performing content for this microsegment',
      'Consider A/B testing subject lines for even better results',
      'Optimal send time: Tuesday 9-11am EST',
    ],
  },
  {
    contentId: 'CNT-2024-0001',
    microsegmentId: 'MSEG-002',
    resonanceScore: 78,
    historicalData: [
      {
        campaignId: 'CMP-2024-Q3-001',
        openRate: 0.72,
        clickRate: 0.34,
        conversionRate: 0.18,
        sampleSize: 421,
      },
      {
        campaignId: 'CMP-2024-Q2-003',
        openRate: 0.75,
        clickRate: 0.36,
        conversionRate: 0.19,
        sampleSize: 398,
      },
    ],
    predictedMetrics: {
      openRate: 0.74,
      clickRate: 0.35,
      conversionRate: 0.19,
      confidence: 0.78,
    },
    recommendations: [
      'Strong performer for mid-tier engagement group',
      'Test with regional case studies to boost relevance',
    ],
  },
  {
    contentId: 'CNT-2024-0001',
    microsegmentId: 'MSEG-003',
    resonanceScore: 64,
    historicalData: [
      {
        campaignId: 'CMP-2024-Q3-001',
        openRate: 0.61,
        clickRate: 0.28,
        conversionRate: 0.14,
        sampleSize: 289,
      },
    ],
    predictedMetrics: {
      openRate: 0.61,
      clickRate: 0.28,
      conversionRate: 0.14,
      confidence: 0.62,
    },
    recommendations: [
      'Below-average performance for this group',
      'Consider simpler messaging or different content type',
      'Test paid display ads as alternative channel',
    ],
  },
  {
    contentId: 'CNT-2024-0001',
    microsegmentId: 'MSEG-004',
    resonanceScore: 85,
    historicalData: [
      {
        campaignId: 'CMP-2024-Q2-007',
        openRate: 0.82,
        clickRate: 0.39,
        conversionRate: 0.24,
        sampleSize: 156,
      },
    ],
    predictedMetrics: {
      openRate: 0.82,
      clickRate: 0.39,
      conversionRate: 0.24,
      confidence: 0.71,
    },
    recommendations: [
      'High potential for new-to-brand segment',
      'Pair with welcome series for maximum impact',
    ],
  },

  // CNT-2024-0011 (LinkedIn Thought Leadership) predictions
  {
    contentId: 'CNT-2024-0011',
    microsegmentId: 'MSEG-001',
    resonanceScore: 88,
    historicalData: [
      {
        campaignId: 'CMP-2024-Q3-002',
        openRate: 0.84,
        clickRate: 0.48,
        conversionRate: 0.31,
        sampleSize: 298,
      },
    ],
    predictedMetrics: {
      openRate: 0.84,
      clickRate: 0.48,
      conversionRate: 0.31,
      confidence: 0.74,
    },
    recommendations: [
      'Excellent for thought leaders and academic centers',
      'Leverage influencer quotes for social proof',
    ],
  },
  {
    contentId: 'CNT-2024-0011',
    microsegmentId: 'MSEG-002',
    resonanceScore: 72,
    historicalData: [
      {
        campaignId: 'CMP-2024-Q3-002',
        openRate: 0.68,
        clickRate: 0.32,
        conversionRate: 0.16,
        sampleSize: 412,
      },
    ],
    predictedMetrics: {
      openRate: 0.68,
      clickRate: 0.32,
      conversionRate: 0.16,
      confidence: 0.72,
    },
    recommendations: [
      'Moderate performance for private practice group',
      'Test with more practical, practice-focused messaging',
    ],
  },

  // CNT-2024-0030 (Medscape Banner) predictions
  {
    contentId: 'CNT-2024-0030',
    microsegmentId: 'MSEG-001',
    resonanceScore: 81,
    historicalData: [
      {
        campaignId: 'CMP-2024-Q2-009',
        openRate: 0.76,
        clickRate: 0.41,
        conversionRate: 0.22,
        sampleSize: 1245,
      },
    ],
    predictedMetrics: {
      openRate: 0.76,
      clickRate: 0.41,
      conversionRate: 0.22,
      confidence: 0.88,
    },
    recommendations: [
      'Solid display performance across all tiers',
      'High reach potential via Medscape platform',
    ],
  },
  {
    contentId: 'CNT-2024-0030',
    microsegmentId: 'MSEG-002',
    resonanceScore: 79,
    historicalData: [
      {
        campaignId: 'CMP-2024-Q2-009',
        openRate: 0.74,
        clickRate: 0.38,
        conversionRate: 0.19,
        sampleSize: 987,
      },
    ],
    predictedMetrics: {
      openRate: 0.74,
      clickRate: 0.38,
      conversionRate: 0.19,
      confidence: 0.84,
    },
    recommendations: [
      'Consistent performer across practice types',
      'Medscape is a trusted source for this segment',
    ],
  },
  {
    contentId: 'CNT-2024-0030',
    microsegmentId: 'MSEG-003',
    resonanceScore: 73,
    historicalData: [
      {
        campaignId: 'CMP-2024-Q2-009',
        openRate: 0.69,
        clickRate: 0.34,
        conversionRate: 0.16,
        sampleSize: 654,
      },
    ],
    predictedMetrics: {
      openRate: 0.69,
      clickRate: 0.34,
      conversionRate: 0.16,
      confidence: 0.79,
    },
    recommendations: [
      'Good reach for rural/community segment',
      'Medscape penetration is strong in these areas',
    ],
  },
];

// ID Registry Entries (Sample for an activated campaign)
export const mockIDRegistry: IDRegistryEntry[] = [
  // Campaign-level ID
  {
    id: 'IDR-001',
    type: 'CAMPAIGN',
    compositeKey: 'CMP-EYLEA-2024-001',
    campaignId: 'CMP-EYLEA-2024-001',
    utmParameters: {
      utm_source: 'cmi_media',
      utm_medium: 'multi',
      utm_campaign: 'eylea_hcp_retina_q4_amd',
    },
    cmParameters: {
      cm_journey_id: 'CMP-EYLEA-2024-001',
      cm_node_seq: '-',
      cm_brand: 'eylea',
      cm_audience: 'hcp',
      cm_segment: 'retina_specialists',
      cm_therapeutic_area: 'ophthalmology',
      cm_indication: 'wet_amd',
    },
    mintedAt: new Date('2024-11-01T09:23:15Z'),
    mintedBy: 'sarah.johnson@pharma.com',
    status: 'ACTIVE',
  },

  // Sequence-level IDs
  {
    id: 'IDR-002',
    type: 'SEQUENCE',
    compositeKey: 'CMP-EYLEA-2024-001/SEQ-1',
    campaignId: 'CMP-EYLEA-2024-001',
    sequenceNumber: 1,
    utmParameters: {
      utm_source: 'cmi_media',
      utm_medium: 'email',
      utm_campaign: 'eylea_hcp_retina_q4_amd',
      utm_term: 'SEQ-1',
    },
    cmParameters: {
      cm_journey_id: 'CMP-EYLEA-2024-001',
      cm_node_seq: '1',
      cm_brand: 'eylea',
      cm_audience: 'hcp',
      cm_segment: 'retina_specialists',
      cm_therapeutic_area: 'ophthalmology',
    },
    mintedAt: new Date('2024-11-01T09:23:16Z'),
    mintedBy: 'sarah.johnson@pharma.com',
    status: 'ACTIVE',
  },
  {
    id: 'IDR-003',
    type: 'SEQUENCE',
    compositeKey: 'CMP-EYLEA-2024-001/SEQ-2',
    campaignId: 'CMP-EYLEA-2024-001',
    sequenceNumber: 2,
    utmParameters: {
      utm_source: 'cmi_media',
      utm_medium: 'wait',
      utm_campaign: 'eylea_hcp_retina_q4_amd',
      utm_term: 'SEQ-2',
    },
    cmParameters: {
      cm_journey_id: 'CMP-EYLEA-2024-001',
      cm_node_seq: '2',
      cm_brand: 'eylea',
      cm_audience: 'hcp',
      cm_segment: 'retina_specialists',
      cm_therapeutic_area: 'ophthalmology',
    },
    mintedAt: new Date('2024-11-01T09:23:17Z'),
    mintedBy: 'sarah.johnson@pharma.com',
    status: 'ACTIVE',
  },

  // Content-level IDs (with microsegment tracking)
  {
    id: 'IDR-004',
    type: 'CONTENT',
    compositeKey: 'CMP-EYLEA-2024-001/SEQ-1/CNT-2024-0001',
    campaignId: 'CMP-EYLEA-2024-001',
    sequenceNumber: 1,
    contentId: 'CNT-2024-0001',
    microsegmentId: 'MSEG-001',
    utmParameters: {
      utm_source: 'cmi_media',
      utm_medium: 'email',
      utm_campaign: 'eylea_hcp_retina_q4_amd',
      utm_content: 'CNT-2024-0001',
      utm_term: 'SEQ-1',
    },
    cmParameters: {
      cm_journey_id: 'CMP-EYLEA-2024-001',
      cm_node_seq: '1',
      cm_microsegment_id: 'high_engagers_urban',
      cm_brand: 'eylea',
      cm_audience: 'hcp',
      cm_segment: 'retina_specialists',
      cm_therapeutic_area: 'ophthalmology',
      cm_indication: 'wet_amd',
    },
    mintedAt: new Date('2024-11-01T09:23:18Z'),
    mintedBy: 'sarah.johnson@pharma.com',
    status: 'ACTIVE',
  },
  {
    id: 'IDR-005',
    type: 'CONTENT',
    compositeKey: 'CMP-EYLEA-2024-001/SEQ-1/CNT-2024-0001',
    campaignId: 'CMP-EYLEA-2024-001',
    sequenceNumber: 1,
    contentId: 'CNT-2024-0001',
    microsegmentId: 'MSEG-002',
    utmParameters: {
      utm_source: 'cmi_media',
      utm_medium: 'email',
      utm_campaign: 'eylea_hcp_retina_q4_amd',
      utm_content: 'CNT-2024-0001',
      utm_term: 'SEQ-1',
    },
    cmParameters: {
      cm_journey_id: 'CMP-EYLEA-2024-001',
      cm_node_seq: '1',
      cm_microsegment_id: 'medium_engagers_private',
      cm_brand: 'eylea',
      cm_audience: 'hcp',
      cm_segment: 'retina_specialists',
      cm_therapeutic_area: 'ophthalmology',
      cm_indication: 'wet_amd',
    },
    mintedAt: new Date('2024-11-01T09:23:19Z'),
    mintedBy: 'sarah.johnson@pharma.com',
    status: 'ACTIVE',
  },
  {
    id: 'IDR-006',
    type: 'CONTENT',
    compositeKey: 'CMP-EYLEA-2024-001/SEQ-3/CNT-2024-0011',
    campaignId: 'CMP-EYLEA-2024-001',
    sequenceNumber: 3,
    contentId: 'CNT-2024-0011',
    microsegmentId: 'MSEG-001',
    utmParameters: {
      utm_source: 'cmi_media',
      utm_medium: 'paid_social',
      utm_campaign: 'eylea_hcp_retina_q4_amd',
      utm_content: 'CNT-2024-0011',
      utm_term: 'SEQ-3',
    },
    cmParameters: {
      cm_journey_id: 'CMP-EYLEA-2024-001',
      cm_node_seq: '3',
      cm_microsegment_id: 'high_engagers_urban',
      cm_brand: 'eylea',
      cm_audience: 'hcp',
      cm_segment: 'retina_specialists',
      cm_therapeutic_area: 'ophthalmology',
      cm_indication: 'wet_amd',
    },
    mintedAt: new Date('2024-11-01T09:23:20Z'),
    mintedBy: 'sarah.johnson@pharma.com',
    status: 'ACTIVE',
  },
  {
    id: 'IDR-007',
    type: 'CONTENT',
    compositeKey: 'CMP-EYLEA-2024-001/SEQ-4/CNT-2024-0030',
    campaignId: 'CMP-EYLEA-2024-001',
    sequenceNumber: 4,
    contentId: 'CNT-2024-0030',
    microsegmentId: 'MSEG-002',
    utmParameters: {
      utm_source: 'cmi_media',
      utm_medium: 'paid_display',
      utm_campaign: 'eylea_hcp_retina_q4_amd',
      utm_content: 'CNT-2024-0030',
      utm_term: 'SEQ-4',
    },
    cmParameters: {
      cm_journey_id: 'CMP-EYLEA-2024-001',
      cm_node_seq: '4',
      cm_microsegment_id: 'medium_engagers_private',
      cm_brand: 'eylea',
      cm_audience: 'hcp',
      cm_segment: 'retina_specialists',
      cm_therapeutic_area: 'ophthalmology',
      cm_indication: 'wet_amd',
    },
    mintedAt: new Date('2024-11-01T09:23:21Z'),
    mintedBy: 'sarah.johnson@pharma.com',
    status: 'ACTIVE',
  },
];
